[theme]
base = "dark"
primaryColor = "#2ec4b6"
backgroundColor = "#6c757d"
secondaryBackgroundColor = "#353b41"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
# Hide the "Deploy" button and developer menu from the top-right toolbar
toolbarMode = "minimal"
