[theme]
base = "dark"
primaryColor = "#3c6e71"
backgroundColor = "#353535"
secondaryBackgroundColor = "#2a2a2a"
textColor = "#ececec"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
# Hide the "Deploy" button and developer menu from the top-right toolbar
toolbarMode = "minimal"
